/* ==============================================================
 * File generated by Vivado(TM) HLS - High-Level Synthesis
 * from C, C++ and SystemC
 * Version: 2016.4
 * Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
 * ==============================================================
 *
 * CTRL
 * 0x00 : Control signals
 *        bit 0  - ap_start (Read/Write/COH)
 *        bit 1  - ap_done (Read/COR)
 *        bit 2  - ap_idle (Read)
 *        bit 3  - ap_ready (Read)
 *        bit 7  - auto_restart (Read/Write)
 *        others - reserved
 * 0x04 : Global Interrupt Enable Register
 *        bit 0  - Global Interrupt Enable (Read/Write)
 *        others - reserved
 * 0x08 : IP Interrupt Enable Register (Read/Write)
 *        bit 0  - Channel 0 (ap_done)
 *        bit 1  - Channel 1 (ap_ready)
 *        others - reserved
 * 0x0c : IP Interrupt Status Register (Read/TOW)
 *        bit 0  - Channel 0 (ap_done)
 *        bit 1  - Channel 1 (ap_ready)
 *        others - reserved
 * 0x10 : Data signal of HwReg_width
 *        bit 15~0 - HwReg_width[15:0] (Read/Write)
 *        others   - reserved
 * 0x14 : reserved
 * 0x18 : Data signal of HwReg_height
 *        bit 15~0 - HwReg_height[15:0] (Read/Write)
 *        others   - reserved
 * 0x1c : reserved
 * 0x20 : Data signal of HwReg_video_format
 *        bit 15~0 - HwReg_video_format[15:0] (Read/Write)
 *        others   - reserved
 * 0x24 : reserved
 * 0x28 : Data signal of HwReg_bayer_phase
 *        bit 15~0 - HwReg_bayer_phase[15:0] (Read/Write)
 *        others   - reserved
 * 0x2c : reserved
 * (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write,
 *  COH = Clear on Handshake)
 */
#define XDEMOSAIC_AP_CTRL			(0x00)
#define XDEMOSAIC_WIDTH				(0x10)
#define XDEMOSAIC_HEIGHT			(0x18)
#define XDEMOSAIC_OUTPUT_VIDEO_FORMAT		(0x20)
#define XDEMOSAIC_INPUT_BAYER_FORMAT		(0x28)
